export const INVALIDE_COPPER = 'INVALIDE_COPPER';
export const INVALIDE_COPPER_ALLOW_EMPTY = 'INVALIDE_COPPER_ALLOW_EMPTY';
export const INVALIDE_COPPER_META = 'INVALIDE_COPPER_META';
export const INVALIDE_COPPER_RULES = 'INVALIDE_COPPER_RULES';
export const INVALIDE_COPPER_TYPE = 'INVALIDE_COPPER_TYPE';

export const INVALIDE_RULE = 'INVALIDE_RULE';
export const INVALIDE_RULE_ARGS = 'INVALIDE_RULE_ARGS';
export const INVALIDE_RULE_META = 'INVALIDE_RULE_META';
export const INVALIDE_RULE_TEST = 'INVALIDE_RULE_TEST';

export const INVALIDE_TYPE = 'INVALIDE_TYPE';

export const VALIDATION_EMPTY = 'VALIDATION_EMPTY';
export const VALIDATION_RULE = 'VALIDATION_RULE';
export const VALIDATION_TYPE = 'VALIDATION_TYPE';
