export const INVALIDE_RULE = 'INVALIDE_RULE';
export const INVALIDE_RULE_ARGS = 'INVALIDE_RULE_ARGS';
export const INVALIDE_RULE_META = 'INVALIDE_RULE_META';
export const INVALIDE_RULE_TEST = 'INVALIDE_RULE_TEST';
export const VALIDATION_TYPE = 'VALIDATION_TYPE';
export const VALIDATION_RULE = 'VALIDATION_RULE';
