export const INVALIDE_COPR = 'INVALIDE_COPR';
export const INVALIDE_COPR_ALLOW_EMPTY = 'INVALIDE_COPR_ALLOW_EMPTY';
export const INVALIDE_COPR_META = 'INVALIDE_COPR_META';
export const INVALIDE_COPR_RULES = 'INVALIDE_COPR_RULES';
export const INVALIDE_COPR_TYPE = 'INVALIDE_COPR_TYPE';

export const INVALIDE_RULE = 'INVALIDE_RULE';
export const INVALIDE_RULE_ARGS = 'INVALIDE_RULE_ARGS';
export const INVALIDE_RULE_META = 'INVALIDE_RULE_META';
export const INVALIDE_RULE_OPERATOR = 'INVALIDE_RULE_OPERATOR';
export const INVALIDE_RULE_TEST = 'INVALIDE_RULE_TEST';
export const INVALIDE_TEST_RETURN = 'INVALIDE_TEST_RETURN';

export const INVALIDE_TYPE = 'INVALIDE_TYPE';

export const VALIDATION_CONTENT = 'VALIDATION_CONTENT';
export const VALIDATION_EMPTY = 'VALIDATION_EMPTY';
export const VALIDATION_RULE = 'VALIDATION_RULE';
export const VALIDATION_TYPE = 'VALIDATION_TYPE';
