export const INVALIDE_COPR = 'INVALIDE_COPR';
export const INVALIDE_COPR_ALLOW_EMPTY = 'INVALIDE_COPR_ALLOW_EMPTY';
export const INVALIDE_META = 'INVALIDE_META';
export const INVALIDE_RULE = 'INVALIDE_RULE';
export const INVALIDE_OPERATOR = 'INVALIDE_OPERATOR';
export const INVALIDE_TEST_ARGS = 'INVALIDE_TEST_ARGS';
export const INVALIDE_TEST_FUNC = 'INVALIDE_TEST_FUNC';
export const INVALIDE_TEST_RETURN = 'INVALIDE_TEST_RETURN';
export const INVALIDE_TYPE = 'INVALIDE_TYPE';

export const VALIDATION_CONTENT = 'VALIDATION_CONTENT';
export const VALIDATION_EMPTY = 'VALIDATION_EMPTY';
export const VALIDATION_RULE = 'VALIDATION_RULE';
export const VALIDATION_TYPE = 'VALIDATION_TYPE';
